#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${CHEWCODE_BRIDGE_ENV_FILE:-$HOME/.config/chewcode/bridge.env}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE" >&2
  exit 1
fi

source "$ENV_FILE"

NODE_BIN="${CHEWCODE_NODE_BIN:-node}"
APP_ROOT="${CHEWCODE_BRIDGE_HOME:-/usr/lib/chewcode-bridge}"

if [[ -n "${CHEWCODE_BRIDGE_TOKEN:-}" && -z "${BRIDGE_BEARER_TOKEN:-}" ]]; then
  BRIDGE_BEARER_TOKEN="$CHEWCODE_BRIDGE_TOKEN"
fi

if [[ -n "${CHEWCODE_OPENCODE_HOST:-}" && -n "${CHEWCODE_OPENCODE_PORT:-}" && -z "${OPENCODE_BASE_URL:-}" ]]; then
  OPENCODE_BASE_URL="http://${CHEWCODE_OPENCODE_HOST}:${CHEWCODE_OPENCODE_PORT}"
fi

exec env \
  HOST="${HOST:-${CHEWCODE_BRIDGE_HOST:-127.0.0.1}}" \
  PORT="${PORT:-${CHEWCODE_BRIDGE_PORT:-8091}}" \
  OPENCODE_BASE_URL="${OPENCODE_BASE_URL:-http://127.0.0.1:4096}" \
  BRIDGE_BEARER_TOKEN="${BRIDGE_BEARER_TOKEN:-}" \
  PROJECT_ALLOWED_ROOTS="${PROJECT_ALLOWED_ROOTS:-${CHEWCODE_PROJECT_ALLOWED_ROOTS:-}}" \
  PROJECT_REGISTRY_FILE="${PROJECT_REGISTRY_FILE:-${CHEWCODE_PROJECT_REGISTRY_FILE:-}}" \
  CHEWCODE_OPENCODE_BIN="${CHEWCODE_OPENCODE_BIN:-${OPENCODE_BIN:-opencode}}" \
  "$NODE_BIN" "$APP_ROOT/dist/index.js"
